### ISSUE TITLE
Compile Error with -std=c++2b. 

### ISSUE THREAD

**Issue by Seven-Streams** [DarkSharpness/RISC-V-Simulator-Template#1]
When using **-std=c++20**, everything works.
When I use **-std=c++2b** to compile, I get a failure:

In file included from ../include/bit.h:3,
                 from ../include/tools.h:2,
                 from alu.cpp:1:
../include/debug.h: In function ‘void dark::debug::unreachable()’:
../include/debug.h:16:10: error: ‘unreachable’ is not a member of ‘std’; did you mean ‘dark::debug::unreachable’?
   16 |     std::unreachable();
      |          ^~~~~~~~~~~
../include/debug.h:14:26: note: ‘dark::debug::unreachable’ declared here
   14 | [[noreturn]] inline void unreachable() {
      |                          ^~~~~~~~~~~
../include/debug.h:25:1: warning: ‘noreturn’ function does return
   25 | }
      | ^

**Comment by DarkSharpness** [comment]
Hello! This is because your compiler version is too old. We recommend gcc 12 or later. Still, you may handle this problem by compile with -std=c++20 or  upgrage to gcc-12 or later.
Thanks for your bug report!
